name: eql_source_layouts
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - numpy
    - verde
    - pooch
    # Other dependencies
    - matplotlib
    - ipython
    - jupyter
    - pyproj
    # Development dependencies
    - pytest
    - pytest-cov
    - coverage
    - black
    - pylint
    - flake8
    - pip:
        - git+git://github.com/santisoler/harmonica@eql
