name: eql_source_layout
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - numpy
    - scipy
    - matplotlib
    - verde
    - pip:
        - git+git://github.com/santisoler/harmonica@eql
