name: eql-gradient-boosted
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - boule=0.2.0
  - pooch=1.2.0
  - pyproj
  - netcdf4
  - matplotlib
  - cartopy
  - dask
  - tqdm
  - numba
  # Jupyter related dependencies
  - ipython
  - jupyter
  - jupytext
  # Development dependencies
  - pytest
  - pytest-cov
  - coverage
  - black>=20.8b1
  - pylint
  - flake8
  - flake8-bugbear
  - pip:
      - git+https://github.com/fatiando/harmonica@master
  - pip:
      - git+https://github.com/fatiando/verde@master
