name: eql_source_layouts
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - wheel
  - numpy
  - verde=1.5.0
  - boule=0.2.0
  - pyproj
  # Other dependencies
  - matplotlib
  - cartopy
  # Jupyter related dependencies
  - ipython
  - jupyter
  - jupytext
  # Development dependencies
  - pytest
  - pytest-cov
  - coverage
  - black
  - pylint
  - flake8
  - flake8-bugbear
  - pip:
      - git+https://github.com/fatiando/harmonica@master

