name: eql_source_layouts
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - numpy
    - verde=1.5.0
    - harmonica=0.1.0
    - pooch=1.2.0
    - netcdf4
    # Other dependencies
    - matplotlib
    - ipython
    - jupyter
    - pyproj
    - jupytext
    - tqdm
    # Development dependencies
    - pytest
    - pytest-cov
    - coverage
    - black
    - pylint
    - flake8
    - flake8-bugbear
