name: eql-gradient-boosted
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - boule=0.2.0
  - pooch=1.2.0
  - pygmt=0.3.1
  - harmonica=0.2.1
  - verde=1.6.1
  - pyproj
  - netcdf4
  - matplotlib
  - cartopy
  - dask
  - tqdm
  - numba
  # Jupyter related dependencies
  - ipython
  - jupyter
  # Development dependencies
  - pytest
  - pytest-cov
  - coverage
  - black>=20.8b1
  - pylint
  - flake8
  - flake8-bugbear
