name: manuscript

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    #paths:
      #- 'manuscript/**'
  push:
    branches:
      - master
    paths:
      - 'manuscript/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install LaTeX
        run: sudo apt-get install latexmk texlive texlive-xetex texlive-science

      - name: Compile PDF
        run: |
          cd manuscript
          make
          cd _output
          rm -f *.aux *.log *.bbl *.blg *.out *.toc
          touch .nojekyll
          cd ..
          cd ..

      - name: Upload PR mauscript as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: manuscript
          path: manuscript/_output/manuscript.pdf

  publish_pr:
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the built PDF
        uses: actions/download-artifact@v2
        with:
          name: manuscript

      - name: Publish manuscript to PR branch
        # Don't use tags: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        uses: peaceiris/actions-gh-pages@8a36f3edfc5d1cbae6b09e6f5a7d7b19e5b7a73b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: manuscript/_output
          publish_branch: pr-${{ github.event.number }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          # Only keep the latest commit to avoid bloating the repository
          force_orphan: true

  #clean_pr:
    #if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    #runs-on: ubuntu-latest
    #steps:

  publish:
    needs: [build]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the built PDF
        uses: actions/download-artifact@v2
        with:
          name: manuscript

      - name: Publish manuscript to to gh-pages
        # Don't use tags: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        uses: peaceiris/actions-gh-pages@8a36f3edfc5d1cbae6b09e6f5a7d7b19e5b7a73b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: manuscript/_output
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          # Only keep the latest commit to avoid bloating the repository
          force_orphan: true
